# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 10:29
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=90)),
                (
                    "album_cover",
                    models.ImageField(
                        default="No Image", max_length=1000, upload_to=""
                    ),
                ),
                (
                    "album_thumb",
                    models.ImageField(
                        default="No Image", max_length=1000, upload_to=""
                    ),
                ),
                ("album_video", models.CharField(default="No Video", max_length=1000)),
                (
                    "album_description",
                    models.CharField(default="No Description", max_length=1024),
                ),
                (
                    "album_tracklist",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        size=None,
                    ),
                ),
                ("album_genre", models.CharField(default="music", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=90)),
                (
                    "artist_description",
                    models.CharField(default="No Description", max_length=1024),
                ),
                (
                    "artist_photo",
                    models.ImageField(
                        default="No Photo", max_length=1000, upload_to=""
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScrobbleCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_post", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "date_listen",
                    models.BigIntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(1125932400)
                        ],
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrobble_cards",
                        to="api_1.Album",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrobble_cards",
                        to="api_1.Artist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=90)),
                ("length", models.PositiveIntegerField(null=True)),
                ("position", models.CharField(db_index=True, max_length=10, null=True)),
                ("video", models.CharField(default="No video", max_length=1000)),
                ("lyrics", models.CharField(default="No lyrics", max_length=2000)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="api_1.Album",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="api_1.Artist",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="scrobblecard",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scrobble_cards",
                to="api_1.Song",
            ),
        ),
        migrations.AddField(
            model_name="scrobblecard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usernames",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="api_1.Artist",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scrobblecard", unique_together=set([("user", "date_listen")])
        ),
    ]
