# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api_1", "0001_initial")]

    operations = [
        migrations.AlterUniqueTogether(
            name="song", unique_together=set([("title", "artist", "album")])
        )
    ]
