# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 10:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api_1", "0002_auto_20180515_1333")]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="album_tracklist",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100, null=True),
                blank=True,
                null=True,
                size=None,
            ),
        )
    ]
