# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api_1", "0003_auto_20180515_1340")]

    operations = [
        migrations.AlterUniqueTogether(name="scrobblecard", unique_together=set([]))
    ]
