# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-13 20:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api_1", "0004_auto_20180612_2056")]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="album_tracklist",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=10000, null=True),
                blank=True,
                null=True,
                size=None,
            ),
        )
    ]
