# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-27 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api_1", "0005_auto_20180613_2319")]

    operations = [migrations.AlterUniqueTogether(name="song", unique_together=set([]))]
