# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-28 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api_1", "0006_auto_20180627_0953")]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="length",
            field=models.PositiveIntegerField(blank=True, null=True),
        )
    ]
