# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-29 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api_1", "0007_auto_20180628_1023")]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="position",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        )
    ]
