# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-27 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api_1", "0011_auto_20180630_1926")]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="album_genre",
            field=models.CharField(db_index=True, default="music", max_length=100),
        ),
        migrations.AlterField(
            model_name="song",
            name="position",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
