# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-08 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api_1", "0018_auto_20180802_0958")]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="artist_description",
            field=models.CharField(default="No Description", max_length=4096),
        ),
        migrations.AlterField(
            model_name="artist",
            name="artist_photo",
            field=models.ImageField(
                default="noimage.png", max_length=2048, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="scrobblecard",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scrobble_cards_albums",
                to="api_1.Album",
            ),
        ),
        migrations.AlterField(
            model_name="scrobblecard",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scrobble_cards_artists",
                to="api_1.Artist",
            ),
        ),
        migrations.AlterField(
            model_name="scrobblecard",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scrobble_cards_songs",
                to="api_1.Song",
            ),
        ),
    ]
